### ISSUE TITLE
options are required in nonWSDL mode

### ISSUE THREAD

**Issue by kogundele** [TheGeekyM/cvparser#1]
After doing composer update to install the latest master. I get the following.

`
public function parseCvToXml($resume_url)
    {
        if (is_file($resume_url)) {
            $resume_url = base64_encode(file_get_contents($resume_url));
        }
 
        $client = new \SoapClient(config('cvparser.service_url'));
 
        $result = $client->ProcessCV(
            [
                'document_url' => $resume_url,
                'account'      => 'theGeeky'
            ]
        );
 
        return $result->hrxml;
    }

`

"SoapClient::SoapClient(): 'location' and 'uri' options are required in nonWSDL mode"

**Comment by TheGeekyM** [comment]
Enter your url service in config/cvparser file

**Comment by AkinOlawale** [comment]
Hi @TheGeekyM How do I get the service URL and account details? I cannot seem to get it via the website

**Comment by amitgwachha** [comment]
I got the same issue. Have you solved this?

**Comment by TheGeekyM** [comment]
The URL I provided was mine guys and I paid for it, you can solve it by subscribing to **Daxtra** site and they will provide you a URL like this `http://88.198.90.116/cvvalid/CVXtractorService.wsdl`
